set(_AMENT_PACKAGE_NAME "lightning")
set(lightning_VERSION "0.0.0")
set(lightning_MAINTAINER "gaoxiang <gao.xiang.thu@gmail.com>")
set(lightning_BUILD_DEPENDS "rosidl_default_generators" "scrubber_common" "agibot_robot" "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "std_srvs" "tf2" "tf2_ros" "pcl_conversions" "pcl_ros" "message_filters" "visualization_msgs")
set(lightning_BUILDTOOL_DEPENDS "ament_cmake")
set(lightning_BUILD_EXPORT_DEPENDS "scrubber_common" "agibot_robot" "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "std_srvs" "tf2" "tf2_ros" "pcl_conversions" "pcl_ros" "message_filters" "visualization_msgs")
set(lightning_BUILDTOOL_EXPORT_DEPENDS )
set(lightning_EXEC_DEPENDS "rosidl_default_runtime" "scrubber_common" "agibot_robot" "rclcpp" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs" "std_srvs" "tf2" "tf2_ros" "pcl_conversions" "pcl_ros" "message_filters" "visualization_msgs")
set(lightning_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(lightning_GROUP_DEPENDS )
set(lightning_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(lightning_DEPRECATED "")
set(lightning_EXPORT_TAGS)
list(APPEND lightning_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
